project:
  type: book
  output-dir: "output"

sources:
  base: ./input/example/base
  build: ./input/example/build

book:
  title: "ActivitySim Base-Build Comparison Visualization"
  repo-url: https://github.com/ActivitySim/asim_eet_viz
  search: false

  chapters:
    - index.qmd
    - notebooks/long_term.ipynb
    - notebooks/daily.ipynb
    - notebooks/joint.ipynb
    - notebooks/tours.ipynb
    - notebooks/trips.ipynb

format:
  html:
    mainfont: Poppins
    fontsize: "7"
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    echo: false
    code-tools: true
    # output-file: visualization
    embed-resources: true
toc: true
warning: false
