project:
  type: book
  output-dir: "output"

sources:
  affected_zones: ./input/transit_zones_affected.csv
  base: ./input/example/base
  build: ./input/example/build
  how_method: all # Employment -> any, Transit -> all

  notebooks:
  - long_term.ipynb
  - daily.ipynb
  - joint.ipynb
  - tours.ipynb
  - trips.ipynb

book:
  title: "ActivitySim Base-Build Comparison Visualization"
  repo-url: https://github.com/ActivitySim/asim_eet_viz
  search: false

  chapters:
    - index.qmd

number-sections: true
format:
  html:
    mainfont: sans-serif
    fontsize: "7"
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    echo: false
    code-tools: true
    # output-file: visualization
    embed-resources: false
toc: true
warning: false
