---
title: Introduction
date: today
---


# Base-vs.-Build Scenario Comparison Visualizer
This repository contains a set of Jupyter notebooks which
develop summary statistics and charts for visualizing the
comparative results of a base and build scenario. The initial
use case is a bespoke solution for the Explicit Error Terms
project but may be useful for any base-vs.-build scenario
comparison.

## Input Notebooks and Data
The notebooks, stored in the `notebooks` directory, all 
pull base and build data from directories specified in
`_quarto.yml` under the `sources` setting. An example
dataset pair is provided under the `input/example` directory
which acts as the default source in the configuration YAML.
Modify the `sources.base` and `sources.build` settings to
select a different data source.

## Installation
To install the appropriate dependencies for creating the
output visualizations, install the dependencies in the
`environment.yml` file using `conda env create -n {environment_name}`

## Output Compilation
To rebuild the output website, run the `compile.py` script, which
will pull a list of Jupyter notebooks from `_quarto.yml` to
execute. The outputs from these notebooks will be compiled
into the new website, found in the `output` directory.

## Cleaning Notebooks
When compiling the source notebooks, output data and metadata
are generated and stored in the file alongside the source.
In preparation for uploading notebooks to this repository, please remove the output data and metadata to keep the notebooks tidy.
Functionality is included in the `compile.py` script to do this
using the `--clean` command-line argument. For example:
```
python compile.py --clean
```